export interface ServiceItem {
  name: string
  price: number
}

export interface ServiceCategory {
  key: string
  label: string
  description: string
  startingFrom: number
  items: ServiceItem[]
}

export const SERVICES: ServiceCategory[] = [
  {
    key: 'hand-foot',
    label: 'Hand & Foot Spa',
    description: 'Hydrating treatments for hands and feet.',
    startingFrom: 30,
    items: [
      { name: 'Beautyels Hydra Hand Scan Glow', price: 150 },
      { name: 'Velvet Leg Spa', price: 120 },
      { name: 'Foot Scrub', price: 30 },
    ],
  },
  {
    key: 'henna',
    label: 'Henna',
    description: 'Traditional and modern henna designs.',
    startingFrom: 25,
    items: [
      { name: 'Henna Arm (per arm)', price: 40 },
      { name: 'Henna Hand (per hand)', price: 25 },
    ],
  },
  {
    key: 'eyelash',
    label: 'Eyelash',
    description: 'Lash extensions, lifts, and treatments.',
    startingFrom: 75,
    items: [
      { name: 'Eyelash Lifting', price: 150 },
      { name: 'Classic Refill', price: 75 },
      { name: 'Eyebrow Lamination', price: 150 },
      { name: 'Eyelash Removal', price: 80 },
      { name: 'Eyelash Firming', price: 150 },
      { name: 'Eyelash Extension Classic', price: 180 },
      { name: 'Eyelash Extension Volume', price: 200 },
      { name: 'Eyelash Extension Hybrid Lashes', price: 250 },
    ],
  },
  {
    key: 'eyebrow',
    label: 'Eyebrow',
    description: 'Shape, color, shade and define.',
    startingFrom: 30,
    items: [
      { name: 'Eyebrow Shaping', price: 30 },
      { name: 'Eyebrow Color', price: 30 },
      { name: 'Eyebrow Shading', price: 30 },
      { name: 'Eyebrow Bleaching', price: 30 },
    ],
  },
  {
    key: 'threading',
    label: 'Threading',
    description: 'Precise threading for face and brows.',
    startingFrom: 10,
    items: [
      { name: 'Lower Lip', price: 10 },
      { name: 'Upper Lip', price: 15 },
      { name: 'Neck', price: 10 },
      { name: 'Forehead', price: 10 },
      { name: 'Eyebrows', price: 30 },
      { name: 'Sides', price: 20 },
      { name: 'Full Face', price: 50 },
      { name: 'Shaving', price: 50 },
    ],
  },
  {
    key: 'makeup',
    label: 'Makeup',
    description: 'From everyday glam to bridal perfection.',
    startingFrom: 75,
    items: [
      { name: 'Party Makeup', price: 250 },
      { name: 'Daily Makeup with Eyelash', price: 200 },
      { name: 'Eye Makeup', price: 75 },
      { name: 'Bridal Makeup', price: 1500 },
    ],
  },
  {
    key: 'hair-blowdry',
    label: 'Hair — Blow Dry',
    description: 'Silk-smooth blow-dries in every length.',
    startingFrom: 50,
    items: [
      { name: 'Short Hair', price: 50 },
      { name: 'Waist Hair', price: 70 },
      { name: 'Long Hair', price: 100 },
      { name: 'Very Long', price: 130 },
    ],
  },
  {
    key: 'hair-wavy',
    label: 'Hair — Wavy',
    description: 'Sculpted waves and tousled volume.',
    startingFrom: 100,
    items: [
      { name: 'Short Hair', price: 100 },
      { name: 'Waist Hair', price: 150 },
      { name: 'Long Hair', price: 200 },
    ],
  },
  {
    key: 'hair-cut',
    label: 'Hair Cut',
    description: 'Precision cuts and signature styles.',
    startingFrom: 30,
    items: [
      { name: 'Trim with Bangs', price: 80 },
      { name: 'Trim Hair Cut', price: 50 },
      { name: 'Hair Cut Straight', price: 50 },
      { name: 'Hair Cut Layers', price: 110 },
      { name: 'Cut Bangs', price: 30 },
      { name: 'Barbie Hair Cut', price: 50 },
    ],
  },
  {
    key: 'color',
    label: 'Color',
    description: 'From subtle vibrance to runway-ready balayage.',
    startingFrom: 50,
    items: [
      { name: 'Vibrance Color', price: 100 },
      { name: 'Full Hair Color (own color)', price: 100 },
      { name: 'Root Color (own color)', price: 50 },
      { name: 'Balayage/Highlights with Collagen — Short', price: 450 },
      { name: 'Balayage/Highlights with Collagen — Medium', price: 650 },
      { name: 'Balayage/Highlights with Collagen — Long', price: 900 },
      { name: 'Highlights — Short', price: 450 },
      { name: 'Highlights — Medium', price: 670 },
      { name: 'Highlights — Long', price: 950 },
      { name: 'Bleaching with Color — Roots', price: 200 },
      { name: 'Bleaching with Color — Short', price: 400 },
      { name: 'Bleaching with Color — Medium', price: 600 },
      { name: 'Bleaching with Color — Long', price: 800 },
      { name: 'Bleaching with Color — Extra Long', price: 1000 },
      { name: 'One Tone Color — Root', price: 150 },
      { name: 'One Tone Color — Short', price: 200 },
      { name: 'One Tone Color — Medium', price: 300 },
      { name: 'One Tone Color — Long', price: 400 },
      { name: 'Balayage/Highlights — Short', price: 400 },
      { name: 'Balayage/Highlights — Medium', price: 600 },
      { name: 'Balayage/Highlights — Long', price: 850 },
      { name: 'Balayage/Highlights — Extra Long', price: 1000 },
    ],
  },
  {
    key: 'hair-style',
    label: 'Hair Style',
    description: 'Soirée styling and bridal looks.',
    startingFrom: 100,
    items: [
      { name: 'Hair Style', price: 200 },
      { name: 'Barbie Hair Style', price: 100 },
      { name: 'Bridal Hair Style', price: 1000 },
    ],
  },
  {
    key: 'hair-treatment',
    label: 'Hair Treatment',
    description: 'Botox, keratin, cryo, and restorative rituals.',
    startingFrom: 25,
    items: [
      { name: 'Add-on Ampoules (per capsule)', price: 25 },
      { name: '4 Sessions Organic Treatment', price: 400 },
      { name: 'Loreal Hair Treatment', price: 150 },
      { name: '4 Sessions Cryotherapy (pay 3 get 1 free)', price: 750 },
      { name: 'Cryotherapy Ice Cold Treatment', price: 250 },
      { name: 'Sidr Ritual by Beauty Experience', price: 150 },
      { name: 'Natural Oil — Short', price: 100 },
      { name: 'Natural Oil — Medium', price: 150 },
      { name: 'Natural Oil — Long', price: 200 },
      { name: 'Protein Treatment — Root', price: 300 },
      { name: 'Protein Treatment — Short', price: 400 },
      { name: 'Protein Treatment — Medium', price: 500 },
      { name: 'Protein Treatment — Long', price: 800 },
      { name: 'Protein Treatment — Extra Long', price: 1000 },
      { name: 'Hair Botox — Roots', price: 300 },
      { name: 'Hair Botox — Short', price: 500 },
      { name: 'Hair Botox — Medium', price: 600 },
      { name: 'Hair Botox — Long', price: 800 },
      { name: 'Hair Keratin — Roots', price: 300 },
      { name: 'Hair Keratin — Short', price: 400 },
      { name: 'Hair Keratin — Medium', price: 500 },
      { name: 'Hair Keratin — Long', price: 800 },
      { name: 'Hair Keratin — Extra Long', price: 1000 },
      { name: 'Organic Treatment — Short', price: 80 },
      { name: 'Organic Treatment — Medium', price: 100 },
      { name: 'Organic Treatment — Long', price: 120 },
    ],
  },
  {
    key: 'japanese-scalp',
    label: 'Japanese Scalp Spa',
    description: 'The most relaxing 12-step ritual in the city.',
    startingFrom: 250,
    items: [
      { name: 'Japanese Scalp Treatment (Pay 3 + 1 Free)', price: 750 },
      { name: 'Beautyels Signature 12-Step Japanese Scalp Spa', price: 250 },
    ],
  },
  {
    key: 'nails',
    label: 'Nails',
    description: 'AI-printed nail art and full salon menu.',
    startingFrom: 10,
    items: [
      { name: 'AI Smart Nail Art Full Set', price: 200 },
      { name: 'AI Smart Nail (per nail)', price: 30 },
      { name: 'Gel Polish Only', price: 70 },
      { name: 'Soft Gel', price: 180 },
      { name: 'Acrylic Gelish Extension', price: 360 },
      { name: 'Acrylic Nail Extension with Gel Polish', price: 350 },
      { name: 'Overlay Polish Gel', price: 120 },
      { name: 'Cat Eye Gelish Design', price: 120 },
      { name: 'Manicure Classic', price: 50 },
      { name: 'Manicure Gelish', price: 110 },
      { name: 'Pedicure Classic', price: 60 },
      { name: 'Pedicure Gelish', price: 120 },
      { name: 'Nail Art (per nail)', price: 10 },
      { name: '3D Design (per nail)', price: 30 },
      { name: 'Chrome Add-on', price: 50 },
      { name: 'Cut and File', price: 20 },
      { name: 'Gel Polish Removal', price: 30 },
      { name: 'Extension Removal', price: 80 },
      { name: 'Nail Extension Repair (1 finger)', price: 25 },
    ],
  },
  {
    key: 'waxing',
    label: 'Waxing',
    description: 'Gentle, expert waxing across every area.',
    startingFrom: 10,
    items: [
      { name: 'Full Body Waxing (without Bikini)', price: 250 },
      { name: 'Paraffin Wax Feet', price: 70 },
      { name: 'Paraffin Wax Hands', price: 50 },
      { name: 'Full Leg Waxing', price: 50 },
      { name: 'Full Arm Waxing', price: 50 },
      { name: 'Half Arm Waxing', price: 30 },
      { name: 'Half Legs Waxing', price: 30 },
      { name: 'Full Face Waxing', price: 50 },
      { name: 'Eyebrow Waxing', price: 20 },
      { name: 'Upper Lip Waxing', price: 10 },
      { name: 'Armpit Waxing', price: 30 },
      { name: 'Face Bleaching', price: 50 },
    ],
  },
  {
    key: 'facial',
    label: 'Facial',
    description: 'Targeted cleansing and luminous skin care.',
    startingFrom: 100,
    items: [
      { name: 'Mini Facial', price: 100 },
      { name: 'Deep Cleansing Facial', price: 200 },
    ],
  },
  {
    key: 'massage',
    label: 'Massage',
    description: 'Restorative bodywork in private suites.',
    startingFrom: 30,
    items: [
      { name: '15 Minutes Massage', price: 30 },
      { name: '30 Minutes Massage', price: 75 },
      { name: '1 Hour Massage', price: 150 },
    ],
  },
]
